# This is a basic workflow to help you get started with Actions

name: SubscriptionEmails

# Controls when the action will run. 
on:
  #Runs when a file in specified path is changed
  push:
    paths: '_blog_posts/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get All Changed Files
        uses: jitterbit/get-changed-files@v1
        id: Jitterbit
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      # - id: Jitterbug
      #   uses: jitterbit/get-changed-files@v1
      #   with:
      #     format: 'space-delimited'
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # Decrypts email credentials for use
      - name: Decrypt Credentials
        run: ./_subscription_process/decrypt-credentials.sh
        env:
          CREDENTIALS_PASSPHRASE: ${{ secrets.CREDENTIALS_PASSPHRASE }}

      # Finds what file were changed in the last commit
      - name: Get Files Changed
        run: |
          touch file_names.txt
          files_changed=${{ steps.Jitterbit.outputs.all }}
          echo "$files_changed" > file_names.txt
          echo "::debug:: $files_changed"
        
      # Sets up python
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Installs Python Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
          pip install pybase64
          pip install email-to
          
      # Runs the script
      - name: Run Script
        run: |
          cd _subscription_process
          python automation.py
